/// <reference path="./sst-env.d.ts" />

/**
 * Template: sst.config.ts
 *
 * Generated by `npx @lsts_tech/infra init`.
 * Provider support in v1.0.0: AWS only.
 */

export default $config({
  app(input: any) {
    return {
      name: process.env.INFRA_APP_NAME ?? "__APP_NAME__",
      removal: input?.stage === "production" ? "retain" : "remove",
      protect: ["production"].includes(input?.stage),
      home: "aws",
      providers: {
        aws: {
          region: process.env.AWS_REGION ?? "us-east-1",
        },
      },
    };
  },
  async run() {
    const { createInfrastructure } = await import("./infra.config.js");
    return createInfrastructure();
  },
});
